#!/usr/bin/env python3
"""Build a WordPress WXR file so note.com can import a post with its original date."""

from __future__ import annotations

import base64
import re
import sys
import zipfile
from html import escape
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from md_to_html import md_to_blocks  # noqa: E402
from sdgs_text import CDN_TO_FILE, apply_ja_editorial  # noqa: E402

RAW = (
    "https://raw.githubusercontent.com/kohnoda-glitch/kocorolab/"
    "cursor/note-medium-writing-4caf/writing/drafts/ja-to-note/images"
)

PROFILES = {"18.jpg", "19.jpg", "20.jpg", "21.jpg"}


def strip_source(text: str) -> str:
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        text = text[end + 5 :]
    text = re.sub(r"!\[\]\(https://medium.com/_/stat[^)]+\)\n*", "", text)
    text = re.sub(r"\n---\n\n\[.*was originally published.*\n?", "\n", text)
    return text.strip() + "\n"


def rewrite_img(
    url: str,
    *,
    cdn_map: dict[str, str] | None = None,
    raw: str | None = None,
    profiles: set[str] | None = None,
) -> tuple[str, str]:
    mapping = cdn_map if cdn_map is not None else CDN_TO_FILE
    base = raw if raw is not None else RAW
    prof = profiles if profiles is not None else PROFILES
    name = mapping.get(url)
    if not name:
        raise ValueError("unmapped image (would break when Medium Japanese is replaced): " + url)
    style = "max-width:320px;height:auto" if name in prof else "max-width:100%;height:auto"
    return f"{base}/{name}", f'style="{style}"'


def data_uri(path: Path) -> str:
    """Embed a local image so note's WordPress import does not have to fetch a URL."""
    raw = path.read_bytes()
    mime = {
        ".png": "image/png",
        ".gif": "image/gif",
        ".webp": "image/webp",
    }.get(path.suffix.lower(), "image/jpeg")
    return f"data:{mime};base64,{base64.b64encode(raw).decode('ascii')}"


def embed_local_images(html: str, url_to_path: dict[str, Path]) -> str:
    """Replace remote <img src> URLs with data URIs from files on disk."""
    out = html
    for url, path in url_to_path.items():
        uri = data_uri(path)
        out = out.replace(escape(url, quote=True), uri)
        out = out.replace(url, uri)
    return out


def html_body(
    md: str,
    *,
    cdn_map: dict[str, str] | None = None,
    raw: str | None = None,
    profiles: set[str] | None = None,
) -> tuple[str, str]:
    title, body = md_to_blocks(strip_source(md))

    def repl(m: re.Match[str]) -> str:
        src, style = rewrite_img(
            m.group(1), cdn_map=cdn_map, raw=raw, profiles=profiles
        )
        return f'<p><img src="{escape(src, quote=True)}" alt="" {style}></p>'

    body = re.sub(r'<p><img src="([^"]+)" alt=""></p>', repl, body)
    return title, body


def wxr(
    title: str,
    body: str,
    url: str,
    *,
    local_dt: str = "2020-10-08 12:00:00",
    gmt_dt: str = "2020-10-08 03:00:00",
    pub_rfc: str = "Thu, 08 Oct 2020 03:00:00 +0000",
    post_name: str = "sdgs-goal-1-africa",
) -> str:
    # note.com rejects files that lack the wfw namespace, even though
    # comments are unused. Match a real WordPress WXR 1.2 export.
    safe_url = escape(url, quote=True)
    created = local_dt[:16]
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- generator="WordPress/6.4.3" created="{created}" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
	<title>Kocoro Lab</title>
	<link>https://kocorolab.com/</link>
	<description>Kocoro Lab</description>
	<pubDate>{pub_rfc}</pubDate>
	<language>ja</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>https://kocorolab.com/</wp:base_site_url>
	<wp:base_blog_url>https://kocorolab.com/</wp:base_blog_url>
	<generator>https://wordpress.org/?v=6.4.3</generator>
	<wp:author>
		<wp:author_id>1</wp:author_id>
		<wp:author_login><![CDATA[koheinoda]]></wp:author_login>
		<wp:author_email><![CDATA[koh.noda@gmail.com]]></wp:author_email>
		<wp:author_display_name><![CDATA[野田浩平]]></wp:author_display_name>
		<wp:author_first_name><![CDATA[浩平]]></wp:author_first_name>
		<wp:author_last_name><![CDATA[野田]]></wp:author_last_name>
	</wp:author>
	<item>
		<title><![CDATA[{title}]]></title>
		<link>{safe_url}</link>
		<pubDate>{pub_rfc}</pubDate>
		<dc:creator><![CDATA[koheinoda]]></dc:creator>
		<guid isPermaLink="false">{safe_url}</guid>
		<description></description>
		<content:encoded><![CDATA[{body}]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>1</wp:post_id>
		<wp:post_date><![CDATA[{local_dt}]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[{gmt_dt}]]></wp:post_date_gmt>
		<wp:post_modified><![CDATA[{local_dt}]]></wp:post_modified>
		<wp:post_modified_gmt><![CDATA[{gmt_dt}]]></wp:post_modified_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[{post_name}]]></wp:post_name>
		<wp:status><![CDATA[draft]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[post]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
	</item>
</channel>
</rss>
"""


def write_import_copies(xml_path: Path, easy_name: str = "note-import.xml") -> None:
    """Keep the easy-to-download names in sync with the dated WXR file."""
    easy = xml_path.with_name(easy_name)
    easy.write_bytes(xml_path.read_bytes())
    zpath = easy.with_suffix(".zip")
    with zipfile.ZipFile(zpath, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(easy, arcname=easy.name)
    print("wrote", easy)
    print("wrote", zpath)


def write_browser_page(
    title: str,
    body: str,
    dest: Path | None = None,
    hint: str | None = None,
) -> None:
    """HTML the user can open in a browser and copy into note."""
    esc = escape(title)
    note = hint or (
        "黄色い枠の下にある写真と図を、マウスでなぞって選んでください。"
        " 選んだら <b>⌘C</b>。note の本文をクリックして <b>⌘V</b>。"
        " タイトルは自分で入れてください。"
    )
    html = f"""<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc}</title>
<style>
  body {{ font-family: sans-serif; max-width: 720px; margin: 24px auto; padding: 0 16px; line-height: 1.7; }}
  .note {{ background: #fff6d8; border: 1px solid #e6d48a; padding: 12px 16px; margin-bottom: 24px; }}
  img {{ max-width: 100%; height: auto; }}
</style>
</head>
<body>
<div class="note">
  {note}
</div>
<article id="article">
{body}
</article>
</body>
</html>
"""
    if dest is None:
        dest = ROOT / "writing" / "drafts" / "ja-to-note" / "OPEN-IN-BROWSER.html"
    dest.write_text(html, encoding="utf-8")
    print("wrote", dest)


def main() -> int:
    src = ROOT / "writing" / "source" / "medium-ja"
    matches = list(src.glob("SDGs*.md"))
    if not matches:
        raise SystemExit("Japanese SDGs source not found")
    text = apply_ja_editorial(matches[0].read_text(encoding="utf-8"))
    url = "https://medium.com/koheinoda-11596/sdgs-goal-1-africa"
    m = re.search(r'^url: "([^"]+)"', text, re.M)
    if m:
        url = m.group(1)
    title, body = html_body(text)
    dest = ROOT / "writing" / "drafts" / "ja-to-note" / "2020-10-08-sdgs-goal-1-note-import.xml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(wxr(title, body, url), encoding="utf-8")
    ET.parse(dest)
    write_import_copies(dest)
    write_browser_page(title, body)
    print("wrote", dest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
